from .AdoptanteView import AdoptanteListCreateView, AdoptanteRetrieveUpdateDestroy
from .userAdminView import UserAdminListCreateView,UserAdminRetrieveUpdateDestroy
from .donanteview import DonanteListCreateView,DonanteRetrieveUpdateDestroy,DonanteListAverage
from .mascotaView import MascotaListCreateView, MascotaRetrieveUpdateDestroyAPIView 
from .solicitudView import SolicitudesListCreateView, SolicitudRetrieveUpdateDestroy