# Generated by Django 3.2.7 on 2021-10-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField(default=0, null=True)),
                ('cel', models.IntegerField(default=0, null=True)),
                ('direc', models.TextField(null=True)),
                ('mascotas_fk', models.TextField(null=True)),
                ('adoptantes_fk', models.TextField(null=True)),
            ],
        ),
    ]

