# Generated by Django 3.2.7 on 2021-10-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(choices=[('g', 'Gato'), ('p', 'Perro')], max_length=64)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(choices=[('p', 'Pequeño'), ('m', 'Mediano'), ('p', 'Grande')], max_length=64)),
                ('descripcion', models.TextField(null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=64)),
                ('personalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('esterilizado', models.BooleanField(default=False)),
                ('desparacitado', models.BooleanField(default=False)),
                ('salud', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
