# Generated by Django 3.2.7 on 2021-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('registro_donante', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('nombre', models.TextField()),
                ('objetivo', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
