# Generated by Django 3.2.7 on 2021-10-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0004_auto_20211006_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donante',
            old_name='objetivo',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='donante',
            old_name='nombre',
            new_name='name',
        ),
    ]
