# Generated by Django 3.2.7 on 2021-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0003_adoptante'),
        ('appAdoptame', '0005_auto_20211006_2250'),
    ]

    operations = [
    ]
