# Generated by Django 3.2.7 on 2021-10-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0006_merge_0003_adoptante_0005_auto_20211006_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='desparacitado',
            new_name='desparasitado',
        ),
    ]
