# Generated by Django 3.2.7 on 2021-10-08 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0007_rename_desparacitado_mascota_desparasitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='id',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='cedulaAdoptante',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='telefono',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(default=0)),
                ('resultado', models.BooleanField(null=True)),
                ('adoptante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptantes', to='appAdoptame.adoptante')),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='appAdoptame.mascota')),
            ],
        ),
    ]
