# Generated by Django 3.2.7 on 2021-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0008_auto_20211008_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Tarjeta de crédito'), ('D', 'Tarjeta débito'), ('E', 'Xequi'), ('F', 'Efectivo')], default='', max_length=50),
        ),
    ]
