# Generated by Django 3.2.7 on 2021-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0009_alter_donante_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='transaction_type',
            field=models.CharField(choices=[('A', 'Consignación'), ('B', 'Tarjeta débito'), ('C', 'KviPlata'), ('D', 'Xequi'), ('E', 'Efectivo'), ('F', 'Otro')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
