# Generated by Django 3.2.7 on 2021-10-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0010_auto_20211008_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donante',
            old_name='amount',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='donante',
            old_name='comments',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='donante',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='donante',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='donante',
            old_name='transaction_type',
            new_name='tipo_transaccion',
        ),
    ]
