# Generated by Django 3.2.7 on 2021-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0011_auto_20211015_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('G', 'Gato'), ('P', 'Perro')], max_length=64),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], max_length=64),
        ),
    ]
