# Generated by Django 3.2.7 on 2021-10-30 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0012_auto_20211028_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='personalidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=list, size=3),
        ),
    ]
