# Generated by Django 3.2.7 on 2021-10-31 03:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0014_auto_20211030_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='personalidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=3),
        ),
    ]
