# Generated by Django 3.2.7 on 2021-10-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0015_alter_donante_tipo_transaccion'),
        ('appAdoptame', '0015_alter_mascota_personalidades'),
    ]

    operations = [
    ]
