# Generated by Django 3.2.7 on 2021-10-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0016_merge_20211030_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='comentarios',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
