# Generated by Django 3.2.7 on 2021-10-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdoptame', '0017_alter_donante_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='comentarios',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='tipo_transaccion',
            field=models.CharField(blank=True, choices=[('A', 'Consignación'), ('B', 'Tarjeta débito'), ('C', 'KviPlata'), ('D', 'Xequi'), ('E', 'Efectivo'), ('F', 'Otro')], default='-', max_length=50, null=True),
        ),
    ]
